version: '2'

services:
  scanner:
    restart: always
    build: .
    env_file: .env
    command: node scan_and_post_eddystone_beacons.js
    privileged: true
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "1"
